### ISSUE TITLE
--remove option and option to remove `;`?

### ISSUE THREAD

**Issue by tunnckoCore** [jonschlinkert/lazy-cache-cli#3]
or somthing like that, to remove `utils.js` and update again `package.json`

also something to remove semicolons? cuz currently i do `lazy && standard --format utils.js`

**Comment by jonschlinkert** [comment]
yeah I have a whole refactor that I need to push up. it lets you customize everything. I can't remember what held up publishing it, but thanks for the reminder

**Comment by tunnckoCore** [comment]
Looks to much for me, but okey, lol. Looks good :+1:
